application: journalr-org
version: 1
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- appstats: on
- datastore_admin: on
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /login/google
  script: main.py
  login: required

- url: /admin/.*
  script: main.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /.*
  script: main.py
